### ISSUE TITLE
Reduce number of false duplicates generated by new version of code_agreements()

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qCreate#30]
There are different types of false duplicates generated by `code_agreements()`. Many of them are bilateral agreements signed on the same day. Also a large part is multilateral agreements with the same acronym generated by `code_acronym()` and signature date. 

Find here a list of examples of the false duplicates generated in IEADB:

[https://app.zenhub.com/files/365543800/05b35b32-fa52-4b61-8e5c-6f923620730c/download](https://app.zenhub.com/files/365543800/05b35b32-fa52-4b61-8e5c-6f923620730c/download)

**Comment by EstherPeev** [comment]
Please find below a list of examples of false negatives generated by code_agreements: 

[https://app.zenhub.com/files/365543800/e8786551-154a-49c7-a234-bbc7a8526c1a/download](https://app.zenhub.com/files/365543800/e8786551-154a-49c7-a234-bbc7a8526c1a/download)

As discussed with @henriquesposito, it seems that a majority of them could be solved through `standardise_titles()` (e.g. co-operation -> cooperation, south east -> south-east). 

Another part of them is linked to `code_actions()` and `code_linkages()` finding different actions or linkages depending on the dataset.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev , both documents are incredibly helpful! I have made several changes today to increase matching accuracy for code_agreements(), most of which were guided by the first document you uploaded (on false positives). 

Besides better incorporating code_acronyms() into qID, now actions are extracted for all bilateral agreements so that the issue of several bilateral treaties signed on the same day, which generate false duplicates, is avoided (actions are dropped for all the rest). Some bugs were also fixed with extracting meaningful numbers from agreement titles, linking qIDs to agreements only and with state names.  As well, qIDs now display year only for dates since acronyms are more helpful in distinguishing multilateral treaties.

Now I will focus on the second document you produced, on false negatives. I see that many of the issues derive from patterns and spellings of common words and these can be addressed in standardise_titles(). Others, we have to think about possible ways to del with within code_agreements() and, possibly, consolidate().

**Comment by henriquesposito** [comment]
Some of the new changes with code_agreements() structure should reduce the number of false negatives already (i.e. keeping year only and assigning actions to all bilateral agreements). Some minor changes to standardise_titles() should also fix spelling inconsistencies with some common words. 

@EstherPeev would you please create a new list of false negatives with the new code_agreements() structure? Then we can add more to standardise_titles() and keep on working in trying to improve matching across datasets. 

There is also the issue of ordering to which actions appear for code_actions() which I am currently working on and that, once fix, should increase accuracy in matching and reduce false positives a bit further.

**Comment by EstherPeev** [comment]
Here is the new list of false negatives @henriquesposito 

[https://app.zenhub.com/files/365543800/f9bb54e7-5c31-4e47-9cc9-e541029db1f0/download](https://app.zenhub.com/files/365543800/f9bb54e7-5c31-4e47-9cc9-e541029db1f0/download)

It indeed allowed to reduce the number of false negatives, but there are still few things that could reduce their numbers, either from `standardise_titles()` or `code_states()`.

**Comment by henriquesposito** [comment]
Thank you so much @EstherPeev !

Now could you please try your hand at updating standardise_titles() to remove some of the non-matching patterns found?

Some of the issues in the list are important to consider, for example, adjustment and amendment might be indeed different. While others, as the addition or removal of some words or abbreviations between () might be changed in code_acronyms(), though we would not want all things between parentheses to be removed just the ones that are not too informative as abbreviations (one way to distinguish here might be to look for a limited number, 3-7 of upper case letters and no space and remove these).

One more thing I am considering looking at the qIDs, should we make all acronyms the same size for consistency? We could make them all six letters and for the ones longer than 6 than that we could add numbers in between as we do now, what do you think @EstherPeev?

**Comment by EstherPeev** [comment]
Thank you @henriquesposito for the feedback. Yes, I can take charge of most of the issues related to `standardise_titles()` and `code_states()`.

For `code_acronyms()`, I think you are right, it will make more sense to have the same length for the acronym, independently of the titles' number of words. It is better to be consistent I think. 
There are also few issues that I have seen in the qID acronyms. When the titles contain some punctuation marks (e.g. "," or ":" or "(" or ') the acronym generated include them as well. Only letters or numbers should appear in there.

**Comment by EstherPeev** [comment]
So I was able to take care of most of the issues presented in the last table. The only problem is when two titles that are from the same agreement have one word difference. The typical example is: 

1) Convention For The Protection Of The World Cultural And Natural Heritage
2) Convention **Concerning** The Protection Of The World Cultural And Natural Heritage

In other cases, the extra word was "Marine", "Basin", "Basel" or "Resources". The extra word is generating different acronym in the qID when it should be the same. The simplest way to fix this is maybe to treat them case by case and delete these words for `code_acronyms()`. Do you have any other ideas @henriquesposito ?

Also, the new function `code_agreements()` is generating many false positives (I think it went from 80 to 120, approximately). Maybe a way to deal with this would be to have the uID format as such: YYMMDD instead of only YYYY? Because many of them are bilateral treaties from the same two countries that signed few agreements in the same year (and generally same month) and on the same topic. If we add the month and day, it should generate different qID.

**Comment by henriquesposito** [comment]
Thank you for the feedback @EstherPeev! 

First, I will make code_acronyms() return consistently a 6 digit acronym and we can see how we few about it. 

Second, before changing the dates back to 8 digits, I will change code_actions() so that the order of the actions appear in text matters, this should hopefully work to reduce number of false positives for bilateral agreements. 

Third, now that we import the tm package, I will make sure standardise_titles() does a better job of removing punctuations and other types of pre-processing/cleaning for strings.

**Comment by EstherPeev** [comment]
The new version of `code_agreements` and specially the ordering method of `code_actions()` allowed to reduce the number of false positives. Thanks for that @henriquesposito 

The main types of false positives remaining are the bilateral, signed the same year, with the action "cooperation" (CR) mentioned first. In most of the cases, the treaty titles start the same way and end differently with sometimes a second action mentioned. One solution to implement could be to assign the last action mentioned in the title instead of the first one. What do you think @henriquesposito ?

**Comment by henriquesposito** [comment]
@EstherPeev thank you for the feedback! Good idea for code_actions(), I will update the function to assign the last action instead of the first and, then, we can re-test and see if this solves the issue of false positives for bilateral treaties.

What about false negatives, are we also doing better there? Thank you.

**Comment by henriquesposito** [comment]
Once I updated code_actions() to remove last action only I realized that the issue of false duplicates is simply reversed and not solved . That is, we are assuming that the last (or second) action coded is different between observations (which is not always the case) and, in many cases, the first action is the different one between observations. I will leave the code commented out so @EstherPeev you can re-test and give your opinion. My hint here is that we actually need to find another solution that does not involve extracting the second/last action nor adding a second action.

**Comment by EstherPeev** [comment]
It seems indeed that adding another action or taking the last one does not really help reducing the number of false positives. I tried out these different options as well as the one you proposed @henriquesposito  which is adding the number of words in bracket in the qID. I have first deleted the predictable words from the title, and then added the number of words in the qID. It seems to improve a bit the number of true positives compared to the options described above. 

I have also tried the option of adding the acronym to bilateral, but only the 4 last letters (not 6, like in multilateral). It seems to be the best option so far as it really decreases the number of false positives. I still need to see what is the happening with the number of false negatives. I have added it to the `code_parties()` just to test this option but it might be added elsewhere in the qID. 

The two options described above were added as a comment in the `code_parties()` helper function of `code_agreements()` function.  Let me know what you think and if other options should be considered.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev , this is really helpful!

I like the two solutions you propose, however, I prefer the first (number of words) for two main reasons. First, it is much faster than coding for acronyms, especially if we call code_acronyms(). Moreover, we can do all the operations with base R without importing functions from any other packages. Second, the aesthetics are preferable, in my opinion, as it adds two numbers instead of 4 letters.

I have modified the implementation slightly and added word count to code_parties(). Hopefully, this should solve this issue for false duplicates for bilateral treaties for now.

Thank you!
