### ISSUE TITLE
Create code_activity() function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#35]
The issues with false duplicates being assigned to bilateral treaties continues. Now, instead of code_actions() and counting the number of words in title, let's try to create an acronym for the treaty activity.

**Comment by henriquesposito** [comment]
For testing and simplifications purposes, I updated the code_parties() function so that it returns the acronym of the three last words from bilateral treaties' titles alongside parties coded. There are some adjustments left to do, but it is functioning. As far as I can tell, this appear to solve the issue of false positives for bilateral treaties. I removed counting words from title and code_actions() function as well. These will become unnecessary if this works.

@EstherPeev would you please check and see if the issue with false positives with bilateral treaties has been solved? And, if so, do you think this should become a standalone code_activity() function or left within code_parties() as it currently is?

**Comment by EstherPeev** [comment]
Thanks for setting this up @henriquesposito. 

So after comparison of the number and type of false positives from this version of `code_agreements()` to the former one (with the counting of words and the action), it seems that it does not really decrease the number of false positives for bilateral. However, one positive aspect of this new version is that it really simplifies the qID for bilateral.

I have therefore tried to play around with the new version of the function `code_parties()` to see if the number of false positive could decrease. For example, I have tried to delete the names of the states when creating the abbreviation because some of false positives were ending with the states' name. It allowed to slightly decrease the number of false positives. 

One other option that I have tried was to add the counting of words right before the abbreviation (e.g. FRA-GBR[7ANA]_1783A), it allowed to moderately decrease the number of false positives. 

Another option could be to add some specific words that the function `code_parties()` should ignore when creating the abbreviation (this would be more a case by case solution then). 

What do you think of these solutions @henriquesposito ?

If we decide to continue with this new version of `code_parties()`, I think it might better to have a standalone `code_activity()` function so the user would be able to use `code_parties()` without having the abbreviation in brackets appearing and we could also easily decide if we want to move the activity abbreviation to another position in the qID.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev , this is super helpful! 

I will setup code_activity() as a separate function and implement some of your suggestions as removing the states names before abbreviating last words. As well, I will start to add some specific words to be ignored as alongside months and cities. We can go from there and see what else we can do.

**Comment by henriquesposito** [comment]
code_activity() has been added and re-worked as a separate function. It still need some adjustments but the main function is setup. Adding the function entailed that the countryregex data was copied from qStates and integrated into qCreate. This was done to simplify the extraction of state labels/regex and avoid bugs and unnecessary redundancy. This also means that code_parties() was altered so that the dependency on qStates is no longer necessary for qCreate. 

@EstherPeev would you please take a look at code_parties() and code_activity() and see if it improved on the identification/differentiation of bilateral treaties via qID? Please also add a list of some of the issues you found here so that we can address them. Thank you.

**Comment by EstherPeev** [comment]
Here is the list of the false positives left with the new version of the function: 

[https://app.zenhub.com/files/365543800/e06720af-4e4f-4c95-b06f-543e5c38ced4/download](https://app.zenhub.com/files/365543800/e06720af-4e4f-4c95-b06f-543e5c38ced4/download)

Majority of them could be fixed by adding some words to be ignored in the code_activity() function.

**Comment by EstherPeev** [comment]
I made few changes to `code_agreements()` to solve some of the issues of false positives mentioned in the list above. Some of them were related to the type of agreement not correctly detected (like "Extension of the Agreement...." or "Agreement extending..."). 
I have also added some words in `code_activity()` but to avoid all of the issues cited above, it would require a much longer list of words to add. That might me one solution when another could be to add an extra information the bracket like topic or counting of words.
