### ISSUE TITLE
Issue with export_data() for datasets without bibliography file

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qCreate#42]
export_data() throws an error when we try for export datasets to a database that do not have a bibliography file ? The issue is that most datasets do not come with .bib file when imported and exported in qPackages. 

For the datasets added to qData, for example, we had to add an extra bib file manually in the correct path for the function to work. However, this will create issues for users who will likely not know this or be able to debug this error.

Instead of trying to locate a a .bib file we could just add one template to be filled up by the users? Or find another way around this issue.

**Comment by jhollway** [comment]
Can't this just be made conditional?

**Comment by BBieri** [comment]
I'll have a closer look at it on Monday morning and will try to make the error more explicit. Thanks for the feedback @henriquesposito !

I made this mandatory since `data_source()` relies on this source attribute being attached to the dataset. Moreover, it will shift the burden to the coder of inputting a bibliography and contacting the dataset's owner for permission if one is not readily available rather than on the reviewer (e.g. us). 

As for the approach that @henriquesposito suggests of creating a template, I believe it to be simpler for coders to add the .bib they got from the person at the source of the data rather than users having to input it by themselves.

What do you think?

**Comment by henriquesposito** [comment]
Thank you @BBieri for the explanations. These are good points, but if these are expectations for users/developers these need to be documented in preparation script (i.e. before running export_data(), please add a .bib file to this specific folder...) and the function should return an informative warning to help users/developers know what is causing the issue. 

I also agree that sources are important and that this should be present. So, I would suggest we add more information in preparation script and also how to add a .bib file and where. 

Moreover, I think a template for the cases where this requirement has not been complied with is a good way to proceed for standard formats/fields for .bib files. For concerns with permissions and licenses, we can add a sentence or two in template about making sure permissions to use dataset have been granted and so on.

**Comment by BBieri** [comment]
Great, sounds good @henriquesposito! I'll modify the templates accordingly and will check back in with you on Monday to see if things are clearer that way. I'll also make sure to expand the Develop vignette with a template and some advice on how to write a `.bib` entry.
